<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="resourcePool">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resource" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <!--Personal Background-->
                            <xs:element name="photo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="URI" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="prefix" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="firstName" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="lastName" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="child" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="age" type="xs:duration"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="stressor" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="personalInfo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <!--Professional Background-->
                            <xs:element name="department" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="training" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="qualification" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="workAgreement" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="studies" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                    <xs:attribute name="location" type="xs:string"/> 
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="additionalJob" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                    <xs:attribute name="yearlyRequiredDays" type="xs:duration"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="meansOfTransport" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="professionalInfo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <!--Skills-->
                            <xs:element name="skill" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="v" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <!--Character Traits-->
                            <xs:element name="trait" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="n" type="xs:string" use="required"/>
                                    <xs:attribute name="v">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="0"/>
                                                <xs:maxInclusive value="100"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="age" type="xs:duration" use="required"/>
                        <xs:attribute name="maritalStatus" type="xs:string" use="required"/>
                        <xs:attribute name="profession" type="xs:string" use="required"/>
                        <xs:attribute name="workExperience" type="xs:duration"/>
                        <xs:attribute name="trainingDuration" type="xs:duration"/>
                        <xs:attribute name="weeklyHours" type="xs:duration"/>
                        <xs:attribute name="overtime" type="xs:duration"/>
                        <xs:attribute name="yearlyTimeOf" type="xs:duration" use="required"/>
                        <xs:attribute name="yearlyEducation" type="xs:duration"/>
                        <xs:attribute name="arrivalTime" type="xs:duration"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>