using System.Collections;

namespace flexiTeams.Util;

//https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
public static class ISO_639_1
{
    private static Dictionary<string, string> dict = new()
    {
        {"abkhazian", "ab"},
        {"afar", "aa"},
        {"afrikaans", "af"},
        {"akan", "ak"},
        {"albanian", "sq"},
        {"amharic", "am"},
        {"arabic", "ar"},
        {"aragonese", "an"},
        {"armenian", "hy"},
        {"assamese", "as"},
        {"avaric", "av"},
        {"avestan", "ae"},
        {"aymara", "ay"},
        {"azerbaijani", "az"},
        {"bambara", "bm"},
        {"bashkir", "ba"},
        {"basque", "eu"},
        {"belarusian", "be"},
        {"bengali", "bn"},
        {"bislama", "bi"},
        {"bosnian", "bs"},
        {"breton", "br"},
        {"bulgarian", "bg"},
        {"burmese", "my"},
        {"catalan", "ca"},
        {"valencian", "ca"},
        {"chamorro", "ch"},
        {"chechen", "ce"},
        {"chichewa", "ny"},
        {"chewa", "ny"},
        {"nyanja", "ny"},
        {"chinese", "zh"},
        {"church slavonic", "cu"},
        {"old slavonic", "cu"},
        {"old church slavonic", "cu"},
        {"chuvash", "cv"},
        {"cornish", "kw"},
        {"corsican", "co"},
        {"cree", "cr"},
        {"croatian", "hr"},
        {"czech", "cs"},
        {"danish", "da"},
        {"divehi", "dv"},
        {"dhivehi", "dv"},
        {"maldivian", "dv"},
        {"dutch", "nl"},
        {"flemish", "nl"},
        {"dzongkha", "dz"},
        {"english", "en"},
        {"esperanto", "eo"},
        {"estonian", "et"},
        {"ewe", "ee"},
        {"faroese", "fo"},
        {"fijian", "fj"},
        {"finnish", "fi"},
        {"french", "fr"},
        {"westernfrisian", "fy"},
        {"fulah", "ff"},
        {"gaelic", "gd"},
        {"scottishgaelic", "gd"},
        {"galician", "gl"},
        {"ganda", "lg"},
        {"georgian", "ka"},
        {"german", "de"},
        {"greek", "el"},
        {"modern(1453-)", "el"},
        {"kalaallisut", "kl"},
        {"greenlandic", "kl"},
        {"guarani", "gn"},
        {"gujarati", "gu"},
        {"haitian", "ht"},
        {"haitiancreole", "ht"},
        {"hausa", "ha"},
        {"hebrew", "he"},
        {"herero", "hz"},
        {"hindi", "hi"},
        {"hirimotu", "ho"},
        {"hungarian", "hu"},
        {"icelandic", "is"},
        {"ido", "io"},
        {"igbo", "ig"},
        {"indonesian", "id"},
        {"interlingua", "ia"},
        {"interlingue", "ie"},
        {"occidental", "ie"},
        {"inuktitut", "iu"},
        {"inupiaq", "ik"},
        {"irish", "ga"},
        {"italian", "it"},
        {"japanese", "ja"},
        {"javanese", "jv"},
        {"kannada", "kn"},
        {"kanuri", "kr"},
        {"kashmiri", "ks"},
        {"kazakh", "kk"},
        {"centralkhmer", "km"},
        {"kikuyu", "ki"},
        {"gikuyu", "ki"},
        {"kinyarwanda", "rw"},
        {"kirghiz", "ky"},
        {"kyrgyz", "ky"},
        {"komi", "kv"},
        {"kongo", "kg"},
        {"korean", "ko"},
        {"kuanyama", "kj"},
        {"kwanyama", "kj"},
        {"kurdish", "ku"},
        {"lao", "lo"},
        {"latin", "la"},
        {"latvian", "lv"},
        {"limburgan", "li"},
        {"limburger", "li"},
        {"limburgish", "li"},
        {"lingala", "ln"},
        {"lithuanian", "lt"},
        {"luba-katanga", "lu"},
        {"luxembourgish", "lb"},
        {"letzeburgesch", "lb"},
        {"macedonian", "mk"},
        {"malagasy", "mg"},
        {"malay", "ms"},
        {"malayalam", "ml"},
        {"maltese", "mt"},
        {"manx", "gv"},
        {"maori", "mi"},
        {"marathi", "mr"},
        {"marshallese", "mh"},
        {"mongolian", "mn"},
        {"nauru", "na"},
        {"navajo", "nv"},
        {"navaho", "nv"},
        {"northndebele", "nd"},
        {"southndebele", "nr"},
        {"ndonga", "ng"},
        {"nepali", "ne"},
        {"norwegian", "no"},
        {"norwegianbokmål", "nb"},
        {"norwegiannynorsk", "nn"},
        {"sichuanyi", "ii"},
        {"nuosu", "ii"},
        {"occitan", "oc"},
        {"ojibwa", "oj"},
        {"oriya", "or"},
        {"oromo", "om"},
        {"ossetian", "os"},
        {"ossetic", "os"},
        {"pali", "pi"},
        {"pashto", "ps"},
        {"pushto", "ps"},
        {"persian", "fa"},
        {"polish", "pl"},
        {"portuguese", "pt"},
        {"punjabi", "pa"},
        {"panjabi", "pa"},
        {"quechua", "qu"},
        {"romanian", "ro"},
        {"moldavian", "ro"},
        {"moldovan", "ro"},
        {"romansh", "rm"},
        {"rundi", "rn"},
        {"russian", "ru"},
        {"northernsami", "se"},
        {"samoan", "sm"},
        {"sango", "sg"},
        {"sanskrit", "sa"},
        {"sardinian", "sc"},
        {"serbian", "sr"},
        {"shona", "sn"},
        {"sindhi", "sd"},
        {"sinhala", "si"},
        {"sinhalese", "si"},
        {"slovak", "sk"},
        {"slovenian", "sl"},
        {"somali", "so"},
        {"southernsotho", "st"},
        {"spanish", "es"},
        {"castilian", "es"},
        {"sundanese", "su"},
        {"swahili", "sw"},
        {"swati", "ss"},
        {"swedish", "sv"},
        {"tagalog", "tl"},
        {"tahitian", "ty"},
        {"tajik", "tg"},
        {"tamil", "ta"},
        {"tatar", "tt"},
        {"telugu", "te"},
        {"thai", "th"},
        {"tibetan", "bo"},
        {"tigrinya", "ti"},
        {"tonga", "to"},
        {"tsonga", "ts"},
        {"tswana", "tn"},
        {"turkish", "tr"},
        {"turkmen", "tk"},
        {"twi", "tw"},
        {"uighur", "ug"},
        {"uyghur", "ug"},
        {"ukrainian", "uk"},
        {"urdu", "ur"},
        {"uzbek", "uz"},
        {"venda", "ve"},
        {"vietnamese", "vi"},
        {"volapük", "vo"},
        {"walloon", "wa"},
        {"welsh", "cy"},
        {"wolof", "wo"},
        {"xhosa", "xh"},
        {"yiddish", "yi"},
        {"yoruba", "yo"},
        {"zhuang", "za"},
        {"chuang", "za"},
        {"zulu", "zu"}
    };
    
    public static string GetISO_639_Code(string lang)
    {
        return dict[lang.Trim().ToLower()];
    }
    
    public static List<string> GetISO_639_LanguageNames(string code)
    {
        List<string> lang = new List<string>();
        
        code = code.Trim().ToLower();
        foreach (KeyValuePair<string, string> pair in dict)
        {
            if(pair.Value.Equals(code)) lang.Add(pair.Key);
        }
    }

    
}