namespace FlexiTeams.Util;

//https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
public static class ISO_639_1
{
    private static Dictionary<string, string> _dictLang = new()
    {
        {"abkhazian", "ab"},
        {"afar", "aa"},
        {"afrikaans", "af"},
        {"akan", "ak"},
        {"albanian", "sq"},
        {"amharic", "am"},
        {"arabic", "ar"},
        {"aragonese", "an"},
        {"armenian", "hy"},
        {"assamese", "as"},
        {"avaric", "av"},
        {"avestan", "ae"},
        {"aymara", "ay"},
        {"azerbaijani", "az"},
        {"bambara", "bm"},
        {"bashkir", "ba"},
        {"basque", "eu"},
        {"belarusian", "be"},
        {"bengali", "bn"},
        {"bislama", "bi"},
        {"bosnian", "bs"},
        {"breton", "br"},
        {"bulgarian", "bg"},
        {"burmese", "my"},
        {"catalan", "ca"},
        {"valencian", "ca"},
        {"chamorro", "ch"},
        {"chechen", "ce"},
        {"chichewa", "ny"},
        {"chewa", "ny"},
        {"nyanja", "ny"},
        {"chinese", "zh"},
        {"church slavonic", "cu"},
        {"old slavonic", "cu"},
        {"old church slavonic", "cu"},
        {"chuvash", "cv"},
        {"cornish", "kw"},
        {"corsican", "co"},
        {"cree", "cr"},
        {"croatian", "hr"},
        {"czech", "cs"},
        {"danish", "da"},
        {"divehi", "dv"},
        {"dhivehi", "dv"},
        {"maldivian", "dv"},
        {"dutch", "nl"},
        {"flemish", "nl"},
        {"dzongkha", "dz"},
        {"english", "en"},
        {"esperanto", "eo"},
        {"estonian", "et"},
        {"ewe", "ee"},
        {"faroese", "fo"},
        {"fijian", "fj"},
        {"finnish", "fi"},
        {"french", "fr"},
        {"westernfrisian", "fy"},
        {"fulah", "ff"},
        {"gaelic", "gd"},
        {"scottishgaelic", "gd"},
        {"galician", "gl"},
        {"ganda", "lg"},
        {"georgian", "ka"},
        {"german", "de"},
        {"greek", "el"},
        {"modern(1453-)", "el"},
        {"kalaallisut", "kl"},
        {"greenlandic", "kl"},
        {"guarani", "gn"},
        {"gujarati", "gu"},
        {"haitian", "ht"},
        {"haitiancreole", "ht"},
        {"hausa", "ha"},
        {"hebrew", "he"},
        {"herero", "hz"},
        {"hindi", "hi"},
        {"hirimotu", "ho"},
        {"hungarian", "hu"},
        {"icelandic", "is"},
        {"ido", "io"},
        {"igbo", "ig"},
        {"indonesian", "id"},
        {"interlingua", "ia"},
        {"interlingue", "ie"},
        {"occidental", "ie"},
        {"inuktitut", "iu"},
        {"inupiaq", "ik"},
        {"irish", "ga"},
        {"italian", "it"},
        {"japanese", "ja"},
        {"javanese", "jv"},
        {"kannada", "kn"},
        {"kanuri", "kr"},
        {"kashmiri", "ks"},
        {"kazakh", "kk"},
        {"centralkhmer", "km"},
        {"kikuyu", "ki"},
        {"gikuyu", "ki"},
        {"kinyarwanda", "rw"},
        {"kirghiz", "ky"},
        {"kyrgyz", "ky"},
        {"komi", "kv"},
        {"kongo", "kg"},
        {"korean", "ko"},
        {"kuanyama", "kj"},
        {"kwanyama", "kj"},
        {"kurdish", "ku"},
        {"lao", "lo"},
        {"latin", "la"},
        {"latvian", "lv"},
        {"limburgan", "li"},
        {"limburger", "li"},
        {"limburgish", "li"},
        {"lingala", "ln"},
        {"lithuanian", "lt"},
        {"luba-katanga", "lu"},
        {"luxembourgish", "lb"},
        {"letzeburgesch", "lb"},
        {"macedonian", "mk"},
        {"malagasy", "mg"},
        {"malay", "ms"},
        {"malayalam", "ml"},
        {"maltese", "mt"},
        {"manx", "gv"},
        {"maori", "mi"},
        {"marathi", "mr"},
        {"marshallese", "mh"},
        {"mongolian", "mn"},
        {"nauru", "na"},
        {"navajo", "nv"},
        {"navaho", "nv"},
        {"northndebele", "nd"},
        {"southndebele", "nr"},
        {"ndonga", "ng"},
        {"nepali", "ne"},
        {"norwegian", "no"},
        {"norwegianbokmål", "nb"},
        {"norwegiannynorsk", "nn"},
        {"sichuanyi", "ii"},
        {"nuosu", "ii"},
        {"occitan", "oc"},
        {"ojibwa", "oj"},
        {"oriya", "or"},
        {"oromo", "om"},
        {"ossetian", "os"},
        {"ossetic", "os"},
        {"pali", "pi"},
        {"pashto", "ps"},
        {"pushto", "ps"},
        {"persian", "fa"},
        {"polish", "pl"},
        {"portuguese", "pt"},
        {"punjabi", "pa"},
        {"panjabi", "pa"},
        {"quechua", "qu"},
        {"romanian", "ro"},
        {"moldavian", "ro"},
        {"moldovan", "ro"},
        {"romansh", "rm"},
        {"rundi", "rn"},
        {"russian", "ru"},
        {"northernsami", "se"},
        {"samoan", "sm"},
        {"sango", "sg"},
        {"sanskrit", "sa"},
        {"sardinian", "sc"},
        {"serbian", "sr"},
        {"shona", "sn"},
        {"sindhi", "sd"},
        {"sinhala", "si"},
        {"sinhalese", "si"},
        {"slovak", "sk"},
        {"slovenian", "sl"},
        {"somali", "so"},
        {"southernsotho", "st"},
        {"spanish", "es"},
        {"castilian", "es"},
        {"sundanese", "su"},
        {"swahili", "sw"},
        {"swati", "ss"},
        {"swedish", "sv"},
        {"tagalog", "tl"},
        {"tahitian", "ty"},
        {"tajik", "tg"},
        {"tamil", "ta"},
        {"tatar", "tt"},
        {"telugu", "te"},
        {"thai", "th"},
        {"tibetan", "bo"},
        {"tigrinya", "ti"},
        {"tonga", "to"},
        {"tsonga", "ts"},
        {"tswana", "tn"},
        {"turkish", "tr"},
        {"turkmen", "tk"},
        {"twi", "tw"},
        {"uighur", "ug"},
        {"uyghur", "ug"},
        {"ukrainian", "uk"},
        {"urdu", "ur"},
        {"uzbek", "uz"},
        {"venda", "ve"},
        {"vietnamese", "vi"},
        {"volapük", "vo"},
        {"walloon", "wa"},
        {"welsh", "cy"},
        {"wolof", "wo"},
        {"xhosa", "xh"},
        {"yiddish", "yi"},
        {"yoruba", "yo"},
        {"zhuang", "za"},
        {"chuang", "za"},
        {"zulu", "zu"}
    };
    
    private static Dictionary<string, string> _dictCode = new()
    {
        {"ab", "abkhazian"},
        {"aa", "afar"},
        {"af", "afrikaans"},
        {"ak", "akan"},
        {"sq", "albanian"},
        {"am", "amharic"},
        {"ar", "arabic"},
        {"an", "aragonese"},
        {"hy", "armenian"},
        {"as", "assamese"},
        {"av", "avaric"},
        {"ae", "avestan"},
        {"ay", "aymara"},
        {"az", "azerbaijani"},
        {"bm", "bambara"},
        {"ba", "bashkir"},
        {"eu", "basque"},
        {"be", "belarusian"},
        {"bn", "bengali"},
        {"bi", "bislama"},
        {"bs", "bosnian"},
        {"br", "breton"},
        {"bg", "bulgarian"},
        {"my", "burmese"},
        {"ca", "catalan , valencian"},
        {"ch", "chamorro"},
        {"ce", "chechen"},
        {"ny", "chichewa, chewa, nyanja"},
        {"zh", "chinese"},
        {"cu", "church slavonic, old slavonic, old church slavonic"},
        {"cv", "chuvash"},
        {"kw", "cornish"},
        {"co", "corsican"},
        {"cr", "cree"},
        {"hr", "croatian"},
        {"cs", "czech"},
        {"da", "danish"},
        {"dv", "divehi, dhivehi, maldivian"},
        {"nl", "dutch, flemish"},
        {"dz", "dzongkha"},
        {"en", "english"},
        {"eo", "esperanto"},
        {"et", "estonian"},
        {"ee", "ewe"},
        {"fo", "faroese"},
        {"fj", "fijian"},
        {"fi", "finnish"},
        {"fr", "french"},
        {"fy", "westernfrisian"},
        {"ff", "fulah"},
        {"gd", "gaelic, scottishgaelic"},
        {"gl", "galician"},
        {"lg", "ganda"},
        {"ka", "georgian"},
        {"de", "german"},
        {"el", "greek"},
        {"kl", "kalaallisut, greenlandic"},
        {"gn", "guarani"},
        {"gu", "gujarati"},
        {"ht", "haitian, haitiancreole"},
        {"ha", "hausa"},
        {"he", "hebrew"},
        {"hz", "herero"},
        {"hi", "hindi"},
        {"ho", "hirimotu"},
        {"hu", "hungarian"},
        {"is", "icelandic"},
        {"io", "ido"},
        {"ig", "igbo"},
        {"id", "indonesian"},
        {"ia", "interlingua"},
        {"ie", "interlingue, occidental"},
        {"iu", "inuktitut"},
        {"ik", "inupiaq"},
        {"ga", "irish"},
        {"it", "italian"},
        {"ja", "japanese"},
        {"jv", "javanese"},
        {"kn", "kannada"},
        {"kr", "kanuri"},
        {"ks", "kashmiri"},
        {"kk", "kazakh"},
        {"km", "centralkhmer"},
        {"ki", "kikuyu, gikuyu"},
        {"rw", "kinyarwanda"},
        {"ky", "kirghiz, kyrgyz"},
        {"kv", "komi"},
        {"kg", "kongo"},
        {"ko", "korean"},
        {"kj", "kuanyama, kwanyama"},
        {"ku", "kurdish"},
        {"lo", "lao"},
        {"la", "latin"},
        {"lv", "latvian"},
        {"li", "limburgan, limburger, limburgish"},
        {"ln", "lingala"},
        {"lt", "lithuanian"},
        {"lu", "luba-katanga"},
        {"lb", "luxembourgish, letzeburgesch"},
        {"mk", "macedonian"},
        {"mg", "malagasy"},
        {"ms", "malay"},
        {"ml", "malayalam"},
        {"mt", "maltese"},
        {"gv", "manx"},
        {"mi", "maori"},
        {"mr", "marathi"},
        {"mh", "marshallese"},
        {"mn", "mongolian"},
        {"na", "nauru"},
        {"nv", "navajo, navaho"},
        {"nd", "northndebele"},
        {"nr", "southndebele"},
        {"ng", "ndonga"},
        {"ne", "nepali"},
        {"no", "norwegian"},
        {"nb", "norwegianbokmål"},
        {"nn", "norwegiannynorsk"},
        {"ii", "sichuanyi, nuosu"},
        {"oc", "occitan"},
        {"oj", "ojibwa"},
        {"or", "oriya"},
        {"om", "oromo"},
        {"os", "ossetian, ossetic"},
        {"pi", "pali"},
        {"ps", "pashto, pushto"},
        {"fa", "persian"},
        {"pl", "polish"},
        {"pt", "portuguese"},
        {"pa", "punjabi, panjabi"},
        {"qu", "quechua"},
        {"ro", "romanian, moldavian, moldovan"},
        {"rm", "romansh"},
        {"rn", "rundi"},
        {"ru", "russian"},
        {"se", "northernsami"},
        {"sm", "samoan"},
        {"sg", "sango"},
        {"sa", "sanskrit"},
        {"sc", "sardinian"},
        {"sr", "serbian"},
        {"sn", "shona"},
        {"sd", "sindhi"},
        {"si", "sinhala, sinhalese"},
        {"sk", "slovak"},
        {"sl", "slovenian"},
        {"so", "somali"},
        {"st", "southernsotho"},
        {"es", "spanish, castilian"},
        {"su", "sundanese"},
        {"sw", "swahili"},
        {"ss", "swati"},
        {"sv", "swedish"},
        {"tl", "tagalog"},
        {"ty", "tahitian"},
        {"tg", "tajik"},
        {"ta", "tamil"},
        {"tt", "tatar"},
        {"te", "telugu"},
        {"th", "thai"},
        {"bo", "tibetan"},
        {"ti", "tigrinya"},
        {"to", "tonga"},
        {"ts", "tsonga"},
        {"tn", "tswana"},
        {"tr", "turkish"},
        {"tk", "turkmen"},
        {"tw", "twi"},
        {"ug", "uighur, uyghur"},
        {"uk", "ukrainian"},
        {"ur", "urdu"},
        {"uz", "uzbek"},
        {"ve", "venda"},
        {"vi", "vietnamese"},
        {"vo", "volapük"},
        {"wa", "walloon"},
        {"cy", "welsh"},
        {"wo", "wolof"},
        {"xh", "xhosa"},
        {"yi", "yiddish"},
        {"yo", "yoruba"},
        {"za", "zhuang, chuang"},
        {"zu", "zulu"}
    };
    
    public static string GetCode(string lang )
    {
        if (lang == null || String.IsNullOrWhiteSpace(lang)) throw new ArgumentNullException();
        return _dictLang[lang.Trim().ToLower()];
    }
    
    public static String GetLanguage(string code)
    {
        if (code == null || String.IsNullOrWhiteSpace(code)) throw new ArgumentNullException();
        return _dictCode[code.Trim().ToLower()];
    }

    public static bool IsValidLanguage(String lang)
    {
        if (lang == null || String.IsNullOrWhiteSpace(lang)) throw new ArgumentNullException();
        return _dictLang.ContainsKey(lang.Trim().ToLower());
    }

    public static bool IsValidCode(String code)
    {       
        if (code == null || String.IsNullOrWhiteSpace(code)) throw new ArgumentNullException();
        return _dictCode.ContainsKey(code.Trim().ToLower());
    }
    
}