<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs= "http://www.w3.org/2001/XMLSchema">

	<xs:complexType name= "TaskPool">
        <xs:sequence>
            <xs:element name="Task" type="TaskType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TaskType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ConsumedData" type="ConsumedType"/>
            <xs:element name="ConsumedResource" type="ConsumedType"/>
        </xs:choice>
        <xs:attribute name="id"     type="xs:ID"        use="required"/>
        <xs:attribute name="type"   type="xs:string"    use="required"/>
        <xs:attribute name="venue"  type="xs:string"    use="required"/>
        <xs:attribute name="begin"  type="xs:dateTime"  use="required"/>
		<xs:attribute name="end"    type="xs:dateTime"  use="required"/>
	</xs:complexType>

    <xs:complexType name="ConsumedType">
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>
